apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.duckling.name | quote }}
  name: {{ .Values.duckling.name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.duckling.name | quote }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.duckling.name | quote }}
    spec:
      containers:
      - image: "{{ .Values.duckling.image }}:{{ .Values.duckling.tag }}"
        name: rasa-duckling
        resources: {}
status: {}
