apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.duckling.name | quote }}
  name: {{ .Values.duckling.name | quote }}
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{ .Values.duckling.name | quote }}
  type: NodePort
status:
  loadBalancer: {}
